### ISSUE TITLE
Exchange the first two arguments of `check_csrf/3` for better indexing

### ISSUE THREAD

**Issue by pmoura** [brog45/prologWebScanner#2]
Exchanging the first two arguments of `check_csrf/3` would enable first-argument indexing and avoid a spurious choice-point when calling the predicate:

https://github.com/brog45/prologWebScanner/blob/4772fe02c1cc665895da143c6d5ff426997cb8b1/demo_fuzz_har.pl#L87-L90

See https://www.swi-prolog.org/pldoc/man?section=jitindex for details on SWI-Prolog implementation of indexing.

**Comment by brog45** [comment]
Thanks, Paulo!
